### ISSUE TITLE
运行环境问题

### ISSUE THREAD

**Issue by jersonal** [einQimiaozi/Transformer4keras#1]
您好，感谢您提供的代码，我在运行中碰到了很多环境问题，比如tensorflow和keras，
`from tensorflow.python.keras.engine.base_layer import Layer
ImportError: cannot import name 'Layer'`
等，能否提供一个requirements文件。
我安装了tensorflow-cpu 1.15.0，keras==2.3.1

**Comment by einQimiaozi** [comment]
您好，代码的运行环境需要tensorflow2，如果您想保持tensorflow1的话，将import中所有

```
from tensorflow.keras import xxx
```

修改为

```
from keras import xxx
```

即可
